global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 2
  width: 20
  height: 20
  origin_x: -10
  origin_y: -10
  static_map: true
  rolling_window: true
  resolution: 0.1
